### ISSUE TITLE
Download Link for latest version is broken

### ISSUE THREAD

**Issue by mehrad-rafigh** [kenumir/MaterialSettings#1]
FYI the download link https://bintray.com/kenumir/MaterialDialogs/MaterialSettings/_latestVersion responds with a 404.

**Comment by blackbelt080** [comment]
Page not found 404!!!
Lori 

Sent from AOL Mobile Mail

On Friday, March 20, 2015, Mehrad Rafigh notifications@github.com wrote:

FYI the download link https://bintray.com/kenumir/MaterialDialogs/MaterialSettings/_latestVersion responds with a 404.

**Comment by kenumir** [comment]
I test something - link removed
