### ISSUE TITLE
Erro on add item

### ISSUE THREAD

**Issue by thyerrimezzari** [kenumir/MaterialSettings#11]
Caused by: java.lang.RuntimeException: Binary XML file line #2: You must supply a layout_width attribute.

**Comment by hust201010701** [comment]
This error also confused me for serveralhours,Finally, I found that I missed to make a statement for the theme SettingsActivity .The key code is like this:

	<activity
            android:name=".setting.SettingsActivity"
            android:label="@string/title_activity_settings"
            android:theme="@style/MaterialSettingsTheme"/>
