### ISSUE TITLE
Gradle Project Sync Failed. Please check

### ISSUE THREAD

**Issue by sanathp** [kenumir/MaterialSettings#5]
I am getting the below error when i add the repository and dependency in the gradle file.

Error:Artifact 'appcompat-v7.jar (com.android.support:appcompat-v7:22.0.0)' not found.
Searched in the following locations:
    https://jitpack.io/com/android/support/appcompat-v7/22.0.0/appcompat-v7-22.0.0.jar

**Comment by jitpack-io** [comment]
Usually means the android plugin isn't added to your build file. 

Also you could use this project https://github.com/simpligility/maven-android-sdk-deployer to install android libraries to local maven repository. Then add `mavenCentral()` just before jitpack repository.
