### ISSUE TITLE
Saving Keys of Preferences Not working  

### ISSUE THREAD

**Issue by hmedat** [kenumir/MaterialSettings#7]
I installed the sample example of this library, but when I checked CheckboxItem, then I returned  to open setting Activity, The Value wasn't saved. 

I debugged the sample app, I Found this Code is commented, I removed the comments on this code,

//if (ctx instanceof MaterialSettingsFragment)
//  this.mMaterialSettings = (MaterialSettingsFragment) ctx;

THE SAMPLE EXAMPLE WORKED :D :D

**Comment by kenumir** [comment]
Please download release version - not master.
Master version has some non tested features.

Currently i devlop some others projects and no time for MaterialSettings.

**Comment by hmedat** [comment]
Ok Thanks
